### PR TITLE
fix: generate cache keys of collections using expand_cache_key method

### LINKED ISSUE #8: Caches can't be fetched properly when cache key is an array of active record objects
Hey @pawurb, I wanted to test this gem on our project and found a bug related to the active record collections.

While caching the views we are using 

```ruby
<% cache @grants, namespace: "grants" %>
...
<% end %>
```

And `@grants` is a collection of `ActiveRecord` objects. 

Because the current cache key is changing on every other page load, the cache can't be fetched from the store and we are always writing a new key to the cache-store. 

I took some time to investigate this issue and found out that the problem occurs because of the `cache_key` method on this gem. Looks like Rails retrieves cache keys differently depending on the type of the key. You can see how that works in the `ActiveSupport::Cache` class [here](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/cache.rb#L111).

I'm currently working on a solution to fix this problem, but in the meantime, I wanted to open an issue to track this bug.

### PR DESCRIPTION
**Pull request by eyupatis**
closes #8

### CODE REVIEW

File: lib/rails-brotli-cache/store.rb [hunk 1]
```diff
@@ -41,16 +41,14 @@ def initialize(core_store, options = {})
     def fetch(name, options = nil, &block)
       options = (options || {}).reverse_merge(@init_options)
 
-      if !block_given? && options[:force]
```
Comment (eyupatis) [inline lib/rails-brotli-cache/store.rb:44]: Some of the changes on this PR like replacing `block_given?` with `block` etc. is coming from the `standardrb` gem. I can clean those changes up if you want, but because `standardrb` tries to follow the best practices, I wanted to keep them in the PR.

**Comment by pawurb** [comment]
@eyupatis thanks for the PR! I'm looking forward to merging it, but could add a spec which covers the fix?

**Comment by eyupatis** [comment]
Yeah, sure. I'll work on the tests soon.

**Comment by eyupatis** [comment]
Hey @pawurb, I just pushed some specs for testing what was happening when we were fragment caching using this gem. Let me know if the specs look good or need improvement.

**Comment by pawurb** [comment]
@eyupatis thanks. I'll merge it, but please remove all the code style changes, and other changes not related to this PR.

**Comment by eyupatis** [comment]
Sure. My editor is configured to auto-format the ruby code using `standardrb`. I just removed the styling related changes.

**Comment by pawurb** [comment]
@eyupatis thanks! it was an important fix. It looks like before any `cache_key` apart from strings did not work correctly :/
